Parameters:

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ExampleName
      GroupDescription: !Sub ExampleDescription
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        CidrIp: 10.10.0.0/24
  
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Ref ExampleName
      DBSubnetGroupDescription: Custom subnet group for  RDS example
      SubnetIds: !Split
      - ","
      - Fn::ImportValue:
          !Sub "${EnvironmentName}-PRIV-NETS"

  

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupName: !Ref ExampleName
      Description: Custom Parameter group for RDS Example
      Family: postgres15
      Parameters:
        synchronous_commit: 'off'
        rds.force_ssl: 1

  DBInstance:  
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      AllocatedStorage: '20'
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DBName: exampledb
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: !Ref ExampleName
      VPCSecurityGroups:
      - !Ref SecurityGroup
      Engine: postgres
      EngineVersion: "15.2"
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroup
      MasterUsername: !Ref RdMasterUsername
      MasterUserPassword: !Ref RdsMasterPassword

