Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "udacity-s3-example-with-a-random-suffix"
      AccessControl: Private
      VersioningConfiguration: 
        Status: Enabled
      LifecycleConfiguration:
        Rules:
        - Status: "Enabled"
          NoncurrentVersionExpirationInDays: 10
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionDefault:
          SSEAlgorithm: AES256